# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fb996ca1a7aa12cd15b1bb6b78c1d1dc26d6c583b8e706b74d95c6af38b65912165efe827ac0f4b20190d8f4b7af39ea1b4800e5a077acffafc648dc774382e

test:
  secret_key_base: 2d80afa009f695aba4e95f6e4e9e945f2640db0c893025504e7253d4faa2b6a17faff5ce67ba3e4ef3f743a8ff28a953a7dc9a97dba3885bbf70bca0d677e342

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
